"""Gold-standard predictions at the edges of every feature's plausibility range.

``test_gold_standard.py`` pins each clock's prediction on one seeded random row.
This suite pins two more rows per clock: every feature at its registered lower
bound, and every feature at its registered upper bound. Random inputs land in
the middle of a clock's arithmetic; boundary inputs land where transforms
divide by zero, saturate, or overflow, so the two suites fail differently and
the pair catches more than either alone.

The rows are deliberately extreme. Registry bounds are *plausibility* bounds
chosen to catch unit errors, so a boundary row can be physiologically absurd
(creatinine at 3000 µmol/L, every methylation site at exactly 0). Four clocks
therefore predict ``nan`` or ``inf`` here; those values are pinned as such,
with the reason, rather than skipped — a boundary that stops being non-finite
is a change in a clock's arithmetic and this suite should say so.

Predictions come from ``clocks/weights/*.pt`` rather than from
``pya.pred.load_clock``, so that the values pinned here are the clocks this
release ships rather than whatever is currently published on HuggingFace.
"""

import math
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
import torch

import pyaging as pya
from pyaging.predict._pred_utils import check_features_in_adata, predict_ages_with_model

pytestmark = pytest.mark.full_catalog

WEIGHTS_DIR = Path(__file__).resolve().parents[2] / "clocks" / "weights"

# Count-based modalities are registered as [0, inf): there is no plausible
# maximum read depth. Their "upper bound" row is this many counts per feature —
# an arbitrary but fixed choice, because these predictions get pinned below.
_FALLBACK_SPAN = 10.0


class _SilentLogger:
    """The pipeline's logger interface, quieted."""

    def warning(self, message, indent_level=2):
        pass

    def info(self, message, indent_level=2):
        pass

    def error(self, message, indent_level=2):
        pass

    def start_progress(self, message, indent_level=1):
        pass

    def finish_progress(self, message, indent_level=1):
        pass


def load_boundary_clock(clock_name):
    """Load a clock from local weights, prepared exactly as ``_load_clock_impl`` does.

    Parameters
    ----------
    clock_name : str
        Name of the clock, matching its file in ``clocks/weights``.

    Returns
    -------
    pyagingModel
        The clock in float64 on CPU, in eval mode.
    """
    path = WEIGHTS_DIR / f"{clock_name}.pt"
    if not path.exists():
        pytest.skip(f"{path} is build output; generate it by running clocks/notebooks/{clock_name}.ipynb")
    clock = torch.load(path, weights_only=False)
    clock.to(torch.float64)
    clock.to("cpu")
    clock.eval()
    return clock


def boundary_inputs(model):
    """Return (lower, upper) input rows built from each feature's plausibility range.

    Parameters
    ----------
    model : pyagingModel
        The clock whose features are being bounded.

    Returns
    -------
    tuple of list of float
        Values in ``model.features`` order: each feature at its registered lower
        bound, and each at its upper bound. An unbounded side falls back to 0.0
        below and to ``low + _FALLBACK_SPAN`` above.
    """
    records = pya.utils.resolve_feature_ranges(
        model.features, model.metadata.get("data_type"), getattr(model, "feature_units", None)
    )
    lower, upper = [], []
    for record in records:
        low = record["low"] if math.isfinite(record["low"]) else 0.0
        high = record["high"] if math.isfinite(record["high"]) else low + _FALLBACK_SPAN
        lower.append(low)
        upper.append(high)
    return lower, upper


def predict_at_boundaries(clock_name):
    """Predict a clock's age on its lower-bound row and its upper-bound row."""
    model = load_boundary_clock(clock_name)
    lower, upper = boundary_inputs(model)
    frame = pd.DataFrame([lower, upper], columns=model.features)
    adata = pya.pp.df_to_adata(frame, imputer_strategy="constant", verbose=False)
    check_features_in_adata(adata, model, _SilentLogger())
    predictions = predict_ages_with_model(adata, model, "cpu", 1024, _SilentLogger())
    return [float(value) for value in np.asarray(predictions).ravel()]


_NAN = float("nan")
_INF = float("inf")

# clock name -> [prediction at every feature's lower bound, prediction at its upper bound].
# Generated by clocks/generate_boundary_gold.py; regenerate deliberately, never to
# paper over a change in predictions.
#
# Four entries are non-finite by construction, not by accident:
#   ocampoatac1, ocampoatac2 -- an all-zero lower-bound row has a zero row sum,
#       and their TPM normalisation divides counts by it.
#   phenoage, phenoagesaopaulo -- at the upper bound the Gompertz mortality
#       score saturates at exactly 1.0 in float64, so the log(1 - score) in the
#       mortality-to-age link is log(0).
boundary_gold_standard_dict: dict[str, list[float]] = {
    "abec": [53.68241500854492, -15.81053798004723],
    "adbahadosingh": [0.4820077727448921, 0.0029499873676641433],
    "altumage": [16.33985868955524, 68.41639436920633],
    "bitage": [103.54631805419922, 103.54631805419922],
    "bocklandt": [0.0, 1.0],
    "bohlin": [39.60601370675223, 33.39661503649716],
    "cabec": [42.8285026550293, 14.933932761552569],
    "camilloh3k27ac": [49.9620246887207, -18.552160204073935],
    "camilloh3k27me3": [41.93584060668945, 99.03692525802077],
    "camilloh3k36me3": [42.67360305786133, 18.40511390370449],
    "camilloh3k4me1": [44.224239349365234, 28.89654438649031],
    "camilloh3k4me3": [29.278491973876953, 63.34169024641315],
    "camilloh3k9ac": [43.86186218261719, -80.26652162123777],
    "camilloh3k9me3": [52.79884719848633, -276.3269381433068],
    "camillopanhistone": [44.88914489746094, -92.68159853437689],
    "cellpopage": [11.526789665222168, 2.8253560845914762],
    "compil6": [0.0, 1.2174000268423697],
    "corticalclock": [32.13133364915848, 260.03440033399966],
    "cpgptgrimage3": [-57.93381356044485, 5953.476798139613],
    "cpgptpcgrimage3": [894.5644336233464, 4308.179077823943],
    "ctsliver": [48.328636169433594, 174.7241970449686],
    "cvdwesterman": [0.5, 0.7992437187584864],
    "deconvolutebloodepicbcell": [0.16666666666666666, 0.3010328952176566],
    "deconvolutebloodepiccd4tcell": [0.16666666666666666, 0.13763758495398415],
    "deconvolutebloodepiccd8tcell": [0.16666666666666666, 0.0],
    "deconvolutebloodepicmonocyte": [0.16666666666666666, 0.09498319722442837],
    "deconvolutebloodepicneutrophil": [0.16666666666666666, 0.22489174133303957],
    "deconvolutebloodepicnkcell": [0.16666666666666666, 0.24145458127089148],
    "depressionbarbu": [12.216983795166016, 14.980091600999003],
    "dnamfili": [0.20399999618530273, -0.6060000285506248],
    "dnamfitage": [-29.329183027679893, 197.41816715405292],
    "dnamfitagegaitf": [3.9701342582702637, -0.14242133864900097],
    "dnamfitagegaitm": [3.182527780532837, 1.9042181473923847],
    "dnamfitagegripf": [53.820648193359375, -2.213365226984024],
    "dnamfitagegripm": [43.019752502441406, 28.092356762848794],
    "dnamfitagevo2max": [69.65231323242188, 8.845196422655135],
    "dnamic": [0.7852837443351746, 0.845447496707493],
    "dnamphenoage": [60.66400146484375, 41.8159836884588],
    "dnamstress": [-4.4940690994262695, -4.431084418611135],
    "dnamtl": [7.924779891967773, 8.910432073782431],
    "downsyndrome": [0.0, 7.355333080049604],
    "dunedinpace": [-1.9555108594323103, -1.9555108594323103],
    "dunedinpoam38": [-0.06929805129766464, -0.3849129481241107],
    "eabec": [66.6889419555664, -20.117225829628296],
    "encen100": [73.99471282958984, 60.06905569322407],
    "encen40": [33.3239860534668, 133.10089413417154],
    "ensembleagehumanmouse": [-0.5650804042816162, 2.047305117477663],
    "ensembleagestatic": [2.0136327743530273, 0.8691372842695273],
    "ensembleagestatictop": [5.792726993560791, 5.253883486118866],
    "epicga": [41.92224557059152, 36.54197954759002],
    "epicmithyper": [0.0, 1.0],
    "epicmithypo": [1.0, 0.0],
    "epitoc1": [0.0, 1.0],
    "epitoc2": [-1530.330511276771, 44098.160601789554],
    "epitoc3": [-1275.9451024020536, 34705.88313552608],
    "garagnani": [0.0, 1.0],
    "gliasin": [0.9233328700065613, 186.39933314349037],
    "grimage": [21.91879352518128, 325.8066570967177],
    "grimage2": [33.01686329959439, 246.72275973839533],
    "grimage2adm": [290.1693115234375, 1258.8378679603338],
    "grimage2b2m": [1412953.375, 7812594.379638672],
    "grimage2cystatinc": [1091528.5, 1771770.3921813965],
    "grimage2gdf15": [1975.79833984375, 5366.25955414772],
    "grimage2leptin": [7210.0625, 109012.32786941528],
    "grimage2loga1c": [1.6133555173873901, 1.3121452621908247],
    "grimage2logcrp": [-0.2314484417438507, -4.088019125862047],
    "grimage2packyrs": [-31.99702262878418, 268.6913049907889],
    "grimage2pai1": [-1129.6016845703125, 173305.89318871498],
    "grimage2timp1": [15844.595703125, 57819.85381603241],
    "han": [34.934882044792175, 7.847232681512438],
    "hannum": [0.0, 137.2638970836997],
    "hep": [16.710092544555664, 197.7753479537787],
    "hepatoxu": [15.595000267028809, 26.394999980926514],
    "homeostaticdysregulation": [6.712936463159258, 13.47256683058666],
    "horvath2013": [34.605651795864105, 104.24918355691716],
    "hrsinchphenoage": [52.83340835571289, 54.079931220563594],
    "hypoclock": [1.0, 0.0],
    "intrinclock": [1.0031971932470438, 143.634985034907],
    "kdmage": [43.98866546860373, 928.8782637826209],
    "knight": [41.72579574584961, -25.754139692056924],
    "leecontrol": [13.061820030212402, 31.25805701513309],
    "leerefinedrobust": [30.749662399291992, 38.5763336980599],
    "leerobust": [24.99772071838379, 19.315553079213714],
    "lin": [12.216983795166016, 161.08563315868378],
    "linage2": [-9.20579103022785, 160.03700788210168],
    "mammalian1": [2.184725824174804, 2.6704326829292837],
    "mammalian2": [0.03222992091276597, 16.272480891102056],
    "mammalian3": [-0.01830747482685345, 3.172418931626948],
    "mammalianblood2": [33.41225814531768, 4.390673313769585],
    "mammalianblood3": [8.419058095650175, 21.244766882513375],
    "mammalianfemale": [0.6695959023463177, 0.7662072044434864],
    "mammalianlifespan": [0.0591017756383651, 6.755104887670156],
    "mammalianskin2": [0.046972455466898086, 45.018330120705116],
    "mammalianskin3": [1.3140956369748817, 17.102383960938795],
    "mayne": [24.990264892578125, -24.79727719910443],
    "mccartneyalcohol": [0.0, -11.118727269480587],
    "mccartneybmi": [0.5, 0.18764727816594082],
    "mccartneybodyfat": [0.5, 4.628930888662348e-14],
    "mccartneyeducation": [0.5, 0.007120029186346387],
    "mccartneyhdlcholesterol": [0.5, 0.9939456196768891],
    "mccartneyldlcholesterol": [0.5, 0.004025405037611374],
    "mccartneysmoking": [0.0, 4.013877834135201],
    "mccartneytotalcholesterol": [0.5, 0.10699535637785515],
    "mccartneytotalhdlratio": [0.0, 3.6671329863329447],
    "mccartneywhr": [0.0, -0.5692810568052664],
    "meer": [7.693114734086834, 62.914527978045776],
    "neusin": [20.13146209716797, 151.4373656899479],
    "ocampoatac1": [_NAN, 39.29799673869991],
    "ocampoatac2": [_NAN, 29.708636567550048],
    "pasta": [7.923350750523496, 7.923350750523496],
    "pastamouse": [7.923350750523499, -24.849114627143763],
    "pcdnamtl": [7.832613043538429, 6.494520284746235],
    "pcgrimage": [37.61786390284692, 148.5713336502384],
    "pchannum": [8.02118601640706, 142.12234883699256],
    "pchorvath2013": [44.8146624283883, 26.444964344940068],
    "pcphenoage": [31.3444592443627, 108.80935296714817],
    "pcskinandblood": [3.2062822641737005, 79.2648837596677],
    "pedbe": [1.5784102644133058, 5.168237398241537],
    "petkovich": [8.57928486736982, 22.086736946146456],
    "phenoage": [-32.71822724035877, _INF],
    "phenoagesaopaulo": [-38.329015945657886, _INF],
    "pipekelasticnet": [27.0589739382267, -0.5039864702329188],
    "pipekfilteredh": [34.56628465652466, -0.5602606239218944],
    "pipekretrainedh": [33.27607989311218, -0.5510134396699047],
    "prostatecancerkirby": [6.52400016784668, -0.1549997329711914],
    "reedbmi": [0.0, 0.2289999993517995],
    "reg": [87.39013656108204, 87.39013656108204],
    "replitali": [101.5896224975586, 38.44077153020771],
    "replitalinorm": [75.88005828857422, -13.071768389861973],
    "retroelementagev1": [78.13616180419922, -22.44010336464271],
    "retroelementagev2": [62.07419967651367, 77.90140227278607],
    "senchronoage": [-80.0531997680664, 170.90813799528405],
    "sencultureage": [-254.68170166015625, -39.685278982738964],
    "senmortalityage": [0.0, -52.088371641235426],
    "skinandblood": [12.428819578903841, 102.66671288262296],
    "stemtoc": [0.0, 1.0],
    "stemtocvitro": [0.0, 1.0],
    "stoch": [59.80156707763672, 23.02589857346902],
    "stocp": [92.8310775756836, 12.597052562596218],
    "stocz": [64.8077163696289, 47.143190321250586],
    "stubbs": [0.02923955895734213, 0.02923955895734213],
    "systemsage": [-6.993815352103127, 131.70247230342306],
    "systemsageblood": [-208.37915341127504, 318.27949148447266],
    "systemsagebrain": [-270.8609979394058, 392.86288149491367],
    "systemsageheart": [-27.121265248687944, 133.9021291763246],
    "systemsagehormone": [66.89351834347868, -4.098161901385917],
    "systemsageimmune": [132.3183336120199, 306.7876138797944],
    "systemsageinflammation": [87.04910853963257, 35.29811808756971],
    "systemsagekidney": [43.08023794773223, 142.2298829335231],
    "systemsageliver": [55.149078051582876, 226.2409846516814],
    "systemsagelung": [200.34704598357675, 248.66307302698888],
    "systemsagemetabolic": [-176.01932701244797, 170.0061444508523],
    "systemsagemusculoskeletal": [75.90920716267941, 142.2183778075208],
    "thompson": [30.31719970703125, 162.6196001644057],
    "twelvecelldeconvolutebloodepicbas": [0.08333333333333333, 0.0],
    "twelvecelldeconvolutebloodepicbmem": [0.08333333333333333, 0.0],
    "twelvecelldeconvolutebloodepicbnv": [0.08333333333333333, 0.08742581155765926],
    "twelvecelldeconvolutebloodepiccd4mem": [0.08333333333333333, 0.4199823404849646],
    "twelvecelldeconvolutebloodepiccd4nv": [0.08333333333333333, 0.0010578989733181082],
    "twelvecelldeconvolutebloodepiccd8mem": [0.08333333333333333, 0.0],
    "twelvecelldeconvolutebloodepiccd8nv": [0.08333333333333333, 0.07107754032988854],
    "twelvecelldeconvolutebloodepiceos": [0.08333333333333333, 0.0],
    "twelvecelldeconvolutebloodepicmono": [0.08333333333333333, 0.0],
    "twelvecelldeconvolutebloodepicneu": [0.08333333333333333, 0.16254112792604536],
    "twelvecelldeconvolutebloodepicnk": [0.08333333333333333, 0.0],
    "twelvecelldeconvolutebloodepictreg": [0.08333333333333333, 0.25791528072812425],
    "vidalbralo": [84.69999694824219, 45.69999885559082],
    "weidner": [38.0, 152.59999656677246],
    "wu": [13.705485959847769, -0.08182353116416276],
    "xchrom": [37.72539294158469, 37.72539294158469],
    "ychrom": [-5.046871428315086, -5.046871428315086],
    "yingadaptage": [-511.9742736816406, 809.5999955972957],
    "yingcausage": [86.80816650390625, 216.33643661545648],
    "yingdamage": [543.4315795898438, -507.1749781414401],
    "zhangblup": [91.15396118164062, 91.15396118164062],
    "zhangen": [65.79295349121094, 65.79295349121094],
    "zhangmortality": [0.0, -6.315570134669542],
}


@pytest.mark.parametrize("clock_name", sorted(boundary_gold_standard_dict))
def test_boundary_predictions_match_gold(clock_name):
    np.testing.assert_allclose(
        predict_at_boundaries(clock_name),
        boundary_gold_standard_dict[clock_name],
        rtol=0,
        atol=0.01,
    )


def test_every_shipped_clock_is_pinned():
    """A new clock must arrive with boundary expectations, not silently unpinned."""
    shipped = sorted(path.stem for path in WEIGHTS_DIR.glob("*.pt"))
    if not shipped:
        pytest.skip(f"{WEIGHTS_DIR} is build output; generate it by running the clock notebooks")
    assert shipped == sorted(boundary_gold_standard_dict)
